name: Sync S3 Bucket                #workflow 이름
on: push                            #Event 감지

jobs:
  deploy:
    runs-on: ubuntu-latest          #Job 가상환경 인스턴스
    steps:
    - uses: actions/checkout@main
    - uses: awact/s3-action@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        SOURCE_DIR: './public'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}