name: Sync S3 Bucket                #workflow 이름
on: push                            #Event 감지

jobs:
  test:
    runs-on: ubuntu-latest          #Job 가상환경 인스턴스
    steps:
    - name : Install Dependencies   # 의존파일 설치
      run : npm install
    - name: test code
      run : npm test
  build:
    runs-on: ubuntu-latest          #Job 가상환경 인스턴스
    steps:
    - uses: actions/checkout@master
    - run : npm run build
   
  deploy:
    runs-on: ubuntu-latest          #Job 가상환경 인스턴스
    steps:
    - uses: actions/checkout@master
    - uses: awact/s3-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        SOURCE_DIR: 'build'
        AWS_REGION: 'ap-northeast-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
